# Generated by Django 5.2.1 on 2025-06-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [("can_ban_user", "can ban user"), ("can_stop_mailing", "can stop mailing")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
