# Generated by Django 5.2.1 on 2025-06-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_start", models.DateTimeField(blank=True, null=True, verbose_name="Время отправки")),
                ("date_end", models.DateTimeField(blank=True, null=True, verbose_name="Время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                            ("Завершена", "Завершена"),
                            ("Отключена", "Отключена"),
                        ],
                        default="Создана",
                        max_length=9,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["date_start", "date_end", "status", "message"],
                "permissions": [("can_view_mailing", "can view mailing")],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime_attempt", models.DateTimeField(auto_now_add=True, verbose_name="Время попытки рассылки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=14,
                        verbose_name="Статус",
                    ),
                ),
                ("mail_response", models.TextField(verbose_name="Ответ почтового сервиса")),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["datetime_attempt", "status", "mail_response", "mailing"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("head_letter", models.CharField(max_length=300, verbose_name="Тема_письма")),
                ("body_letter", models.TextField(verbose_name="Тело_письма")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
                "ordering": ["head_letter", "body_letter"],
                "permissions": [("can_view_message", "can view message")],
            },
        ),
        migrations.CreateModel(
            name="UserMail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=150, unique=True, verbose_name="Email")),
                ("fullname", models.CharField(max_length=250, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["email", "fullname"],
                "permissions": [("can_view_user_mail", "can view user_mail")],
            },
        ),
    ]
