# Generated by Django 5.2.1 on 2025-06-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="date_end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="date_start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("Создана", "Создана"), ("Запущена", "Запущена"), ("Завершена", "Завершена")],
                default="Создана",
                max_length=9,
                verbose_name="Статус",
            ),
        ),
    ]
