# Generated by Django 5.2.1 on 2025-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")], max_length=14, verbose_name="Статус"
            ),
        ),
    ]
