# Generated by Django 5.2.1 on 2025-06-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0004_alter_mailing_options_alter_mailingattempt_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                    ("Отключена", "Отключена"),
                ],
                default="Создана",
                max_length=9,
                verbose_name="Статус",
            ),
        ),
    ]
